version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/app1"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/app2"
    schedule:
      interval: "daily"
